env:
  browser: true
  es6: true
  node: true

parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: 2015
  sourceType: module

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:json/recommended
  - plugin:sonarjs/recommended
  - plugin:unicorn/recommended

plugins:
  - import
  - json
  - sonarjs
  - unicorn

rules:
  import/no-unused-modules:
    - "error"

overrides:
  # General test overrides
  - files:
      - "**/*.test.{js,mjs}"
    rules:
      sonarjs/no-duplicate-string: "off"

  # Jest test overrides
  - files:
      - "src/**/*.test.{js,mjs}"
    env:
      jest: true
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
