semi: false
tabWidth: 2
endOfLine: lf
printWidth: 120
singleQuote: false
trailingComma: es5
bracketSameLine: true
quoteProps: consistent
overrides:
  - files:
      - "*.html"
    options:
      tabWidth: 4
