name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Docs
        run: npm run docs

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"
          if-no-files-found: error

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
